# Generated by Django 3.2.5 on 2021-09-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Имя')),
                ('text', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('image', models.FileField(blank=True, upload_to='images/users/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Дети',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Имя')),
                ('text', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('image', models.FileField(blank=True, upload_to='images/users/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.DeleteModel(
            name='SupportModel',
        ),
        migrations.AddField(
            model_name='childmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel', verbose_name='Владелец'),
        ),
    ]
