# Generated by Django 3.2.5 on 2021-09-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер'),
        ),
    ]
