# Generated by Django 3.2.5 on 2021-09-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usermodel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='number',
        ),
        migrations.AddField(
            model_name='childmodel',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер'),
        ),
    ]
