# Generated by Django 3.2.5 on 2021-12-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210930_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/users/', verbose_name='Фото'),
        ),
    ]
