# Generated by Django 3.2.5 on 2021-11-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210930_0157'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='user',
        ),
        migrations.CreateModel(
            name='FileUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.filemodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
            options={
                'verbose_name': 'Отправка файла',
                'verbose_name_plural': 'Отправка файла',
            },
        ),
        migrations.CreateModel(
            name='FileSendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFromId', models.CharField(default='', max_length=300, verbose_name='Отправитель')),
                ('userToId', models.CharField(default='', max_length=300, verbose_name='Получатель')),
                ('status', models.CharField(default='', max_length=300, verbose_name='Статус')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.filemodel')),
            ],
            options={
                'verbose_name': 'Отправка файла',
                'verbose_name_plural': 'Отправка файла',
            },
        ),
    ]
