# Generated by Django 3.2.5 on 2021-11-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210930_0157'),
        ('store', '0002_auto_20211124_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesendmodel',
            name='userFromId',
        ),
        migrations.AddField(
            model_name='filesendmodel',
            name='userFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermodel'),
        ),
    ]
