# Generated by Django 3.2.5 on 2021-11-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211124_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesendmodel',
            name='status',
            field=models.CharField(default='wait', max_length=300, verbose_name='Статус'),
        ),
    ]
