# Generated by Django 3.2.5 on 2021-11-24 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_filesendmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesendmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
