# Generated by Django 3.2.5 on 2021-10-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210930_0157'),
        ('catalog', '0002_auto_20211009_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.storemodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
            options={
                'verbose_name': 'Пользовтель хранилища',
                'verbose_name_plural': 'Пользовтели хранилища',
            },
        ),
    ]
