# Generated by Django 3.2.5 on 2021-10-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210930_0157'),
        ('catalog', '0004_blockmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentitymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermodel'),
        ),
    ]
