# Generated by Django 3.2.5 on 2021-11-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_fileentitymodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='type',
            field=models.CharField(default='', max_length=300, verbose_name='Название'),
        ),
    ]
