# Generated by Django 3.2.5 on 2021-11-22 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_storemodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentitymodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
