# Generated by Django 3.2.5 on 2021-11-22 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_fileentitymodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileentitymodel',
            name='entity',
            field=models.FileField(blank=True, null=True, upload_to='store/', verbose_name='Фото'),
        ),
    ]
