# Generated by Django 3.2.5 on 2021-11-23 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210930_0157'),
        ('catalog', '0009_auto_20211122_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermodel'),
        ),
    ]
