# Generated by Django 3.2.5 on 2021-11-23 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_storemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
